### PR TITLE
Adding "GetQueue" Function to player.go.

### PR DESCRIPTION
**Pull request by R0qs3T**
I added the function "GetQueue" that pulls the users queue from the new Endpoint:
https://developer.spotify.com/documentation/web-api/reference/#/operations/get-queue

### CODE REVIEW

**Comment by strideynet** [comment]
Any chance you can include a test for this with some dummy data ?

**Comment by R0qs3T** [comment]
Do you have any plans for a new release?

**Comment by strideynet** [comment]
I'll do it now apologies

**Comment by R0qs3T** [comment]
Perfect, thanks!

**Pull request merged**
