### PR TITLE
added link to RapidAPI

### PR DESCRIPTION
**Pull request by phillipseymor**
Hey! I've added a link in your README to Spotify's functions page in RapidAPI. I've done this for a few Spotify SDKs to help those who are reading the READMEs, understand and test the API before use.

### CODE REVIEW

**Comment by zmb3** [comment]
Would you mind pasting a screenshot here of what this looks like?

I have never heard of RapidAPI.  What does it provide that Spotify's Web API console doesn't?

**Comment by phillipseymor** [comment]
Sure thing! Basically, RapidAPI is an abstraction layer for APIs. It allows devs to test out an API directly in our dashboard to ultimately understand what the response will look like. Most APIs don't have a robust web console like Spotify, so we want to make it easier for devs to connect to them. That being said, a user can also generate any API call in any language of their choice. We've had over 22,000 API calls with our Spotify package over the last few months.

screen shot 2017-02-07 at 2 34 12 pm

**Comment by phillipseymor** [comment]
Essentially, before a dev implements your Go SDK, they'll be able to play around with what the response will look like. :)

**Comment by zmb3** [comment]
Looks like a cool product, and I see the value for APIs that don't offer similar behavior, but I'm not sure my README is the right place to endorse it.

If I'm understanding correctly, the answer to my question _what does RapidAPI provide that Spotify's console doesnt?_ is unfortunately _not much_.

I'm also not a huge fan of raw HTML in markdown - I think it makes it hard to read in text editors where developers spend most of there time.

I would be open to adding a smaller section to the bottom similar to:

> You may find tools such as Spotify's Web API Console [link] or Rapid API [link] valuable for experimenting with the API.

**Comment by zmb3** [comment]
Thanks!

**Pull request merged**
