### PR TITLE
Add AuthURLWithDialog to force app authentication with Spotify

### PR DESCRIPTION
**Pull request by linux-jedi**
#94 Added a new showDialog boolean to the `Authenticator` struct and a setter method for it. For now, it is initialized to false by default. I didn't want to break the existing API/flow, so I didn't add it to the constructor or existing configuration methods. I would love any feedback/suggestions/changes as I am not super familiar with Go code bases :)

### CODE REVIEW

**Comment by zmb3** [comment]
I would probably not worry about breaking the API and would instead make `showDialog` an argument to `AuthURL`.

**Comment by linux-jedi** [comment]
Can we merge these changes?

**Comment by zmb3** [comment]
Sorry @linux-jedi - didn't see your update.  Just one small request - can we _not_ export the show dialog constant?  (I'm not convinced we need a constant at all since there's only one use, but if we must have it, lets at least keep it internal to the package.)

**Comment by linux-jedi** [comment]
I went ahead and just removed the constant. I agree – it is only being used once, so there's no real need for it.

**Comment by zmb3** [comment]
Nice, thanks. I think we can remove the show dialog Boolean arg as well since there’s no need to have the toggle there. If you don’t want the dialog you just call the original method instead.

**Comment by linux-jedi** [comment]
Nice catch. Totally was not thinking when I changed it from my original approach.

**Comment by zmb3** [comment]
Thanks @linux-jedi!  Sorry for the delay.

**Pull request merged**
