### PR TITLE
Use Go 1.8 and 1.9 for CI

### PR DESCRIPTION
**Pull request by adamo57**

### CODE REVIEW

**Comment by zmb3** [comment]
Thanks for this.  Let's remove 1.7 and just keep 1.8 and 1.9.

**Comment by adamo57** [comment]
Personally, I think it's better to test all of the previous go versions from when you started this project

**Comment by zmb3** [comment]
That’s not necessary. This is a simple library. Go has a good compatibility promise.

**Comment by adamo57** [comment]
Ok! Updated

**Pull request merged**
